services:
  nzip-server:
    container_name: nzip-server
    image: ghcr.io/icebrick01/nzip:latest
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - API_URL=${API_URL}
      - IMAGE_URL=${IMAGE_URL}
      - ANALYTICS=${ANALYTICS}
      - DEV=${DEV}
    network_mode: bridge
    restart: unless-stopped